language: ruby

rvm:
- 2.1

install: bundle install
script: jekyll build 

branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
    secure: "t0CWBSS7Kc7Fh+l4Sx3B2xDmexz0RJCYTNJlFSfQT1PCI60bPq1RE4ZbyFRR0w+YLl5ED
GKFAf+0paB4q/Sb/yG3m5wbuTHzjoRbLQR0eXbjNtUsO7MMXRkUy0P/9qR2uT8P+1jP4oonDp23LpMgk
elgE8UMBF9ZLOx21jOizjtfenpdBJHcngs5nsa5Sm4iGa9tCFgTCg5ulN7K+SxQdbht65jk1J0gzNfpH
YWZvQHQPgpeIEF2R9ZgKg8vbn6a0hUNfRe+M9w9g85380rjLXib+7Sjb70x8ipQbchrJUWn7cPQXddht
tJ/PZhg2WGb3BENb1qn1DVzD0/D3qbphw1T/ER8LaioIQFm5kYCEqEY/Y75t0XEVopv1R3Q7cZhgzfYT
Ec24OWbkI3ZaVpUn38TiHmQVGQskryZrsz220DH+rf9EedIS+khrdD+i6gCj8fUnXlLTTpZO5JAC2VsL
rpsLY2fkFhoOTQcodObaoKpu55wafcWjDI9XBDPWf7Tj+BfRjpk1H9mo0MSkZ0Ig6COf2TaL1y5TkHIS
b7XCy6qvBj1Gxrs8mQqbUZx7ZadcZM3wv1zym6+WW1GPs/yebjyJ7P6HLG7TPxVT37naRUZqM5JML1lY
nhnn6duyi/LAOZ5EgtHYqvqSLbiAvIDtwzxYz05vyOwdjDV7s3n34s="
